# Generated by Django 4.2.7 on 2023-11-20 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0003_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
